import Link from "next/link";

export default function TermsPage() {
  return (
    <main className="min-h-screen py-12 px-4">
      <div className="max-w-2xl mx-auto space-y-6">
        <Link href="/" className="font-heading text-2xl font-bold">
          Lullo
        </Link>

        <div>
          <h1 className="font-heading text-3xl font-bold mb-2">
            Terms of Service
          </h1>
          <p className="text-xs text-muted-foreground">
            Last updated: April 2026
          </p>
        </div>

        <section className="space-y-2">
          <h2 className="font-heading text-xl font-semibold">1. Using Lullo</h2>
          <p className="text-sm leading-relaxed">
            Lullo generates personalised bedtime stories for children using AI.
            By using the service, you confirm you are at least 18 years old and
            agree to use it for lawful purposes only. You are responsible for
            any content you generate and for making sure it is appropriate for
            the child you are creating stories for.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="font-heading text-xl font-semibold">
            2. Free and paid plans
          </h2>
          <p className="text-sm leading-relaxed">
            The free plan includes a limited number of stories per month. Lullo
            Plus is a paid subscription billed monthly in US dollars through
            Stripe. You can cancel at any time through your account settings.
            Cancellations take effect at the end of the current billing period.
            We do not offer refunds for partial months.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="font-heading text-xl font-semibold">
            3. AI-generated content
          </h2>
          <p className="text-sm leading-relaxed">
            Stories are generated by AI and may contain unexpected content.
            While we do our best to keep output safe and age-appropriate, we
            cannot guarantee every story will meet your expectations. Please
            review stories before sharing them with your child.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="font-heading text-xl font-semibold">
            4. Your account
          </h2>
          <p className="text-sm leading-relaxed">
            You sign in with Google. You are responsible for keeping your
            account secure. You can delete your account at any time from the
            settings page. Deleting your account removes your saved stories and
            your profile from our systems. Plus subscribers must cancel their
            subscription before deleting their account.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="font-heading text-xl font-semibold">
            5. Changes and termination
          </h2>
          <p className="text-sm leading-relaxed">
            We may update these terms from time to time. We will let you know
            about major changes. We reserve the right to suspend accounts that
            violate these terms or abuse the service.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="font-heading text-xl font-semibold">6. Contact</h2>
          <p className="text-sm leading-relaxed">
            Questions about these terms? Email us at hello@hellolullo.com.
          </p>
        </section>
      </div>
    </main>
  );
}
